<a href="https://colab.research.google.com/github/ornellajogi/Team-3-WoTech-July-6-2024-/blob/main/July_6_(WoTech)_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We have pandas series and pandas framework

In [ ]:
import pandas as pd

In [ ]:
data_list = [1,2,3,4,5]
print(data_list)

[1, 2, 3, 4, 5]

In [ ]:
series_from_list = pd.Series(data_list)
print(series_from_list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
dataframe_from_list = pd.DataFrame(data_list)
print(dataframe_from_list)

   0
0  1
1  2
2  3
3  4
4  5

### Pandas Series from DataFrame

In [ ]:
data_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50}

dataframe_from_dict = pd.Series(data_dict)
print(dataframe_from_dict)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [ ]:
csv_data = "1,2,3,4,5" #string
csv_data.split(',') #split the string into a list

['1', '2', '3', '4', '5']

In [ ]:
series_from_list_split = pd.Series(csv_data.split(','))
print(series_from_list_split)

0    1
1    2
2    3
3    4
4    5
dtype: object

DataFrames![image.png]()

 lists are accessed by index and dictionaries with a key

 lists with [] and dictionaries with {}

In [ ]:
#nested list
data_list = [
    ['John', 30, 68.5, True, 95.5],
    ['Alice', 25, 63.2, False, 88.0],
    ['Bob', 35, 71.0, True, 76.5],
    ['Eve', 28, 65.8, False, 92.0],
    ['Charlie', 40, 72.3, False, 87.5]
]

pd.DataFrame(data_list)
#get default indices and columns

         0   1     2      3     4
0     John  30  68.5   True  95.5
1    Alice  25  63.2  False  88.0
2      Bob  35  71.0   True  76.5
3      Eve  28  65.8  False  92.0
4  Charlie  40  72.3  False  87.5

In [ ]:
column_names = ['Name', 'Age', 'Weight', 'Is Student', 'Score']
pd.DataFrame(data_list, columns = column_names)
#get default indices and columns

      Name  Age  Weight  Is Student  Score
0     John   30    68.5        True   95.5
1    Alice   25    63.2       False   88.0
2      Bob   35    71.0        True   76.5
3      Eve   28    65.8       False   92.0
4  Charlie   40    72.3       False   87.5

In [20]:
df = pd.read_csv('/content/transaction_dataset.csv') # we have read in

In [21]:
df.head()

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics

In [22]:
df.tail() #last 5 rows of df

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [23]:
#can change how many want
df.head(n=10)

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics
5,576539,Monica,Bartlett,F,20/10/2001,99.14,24/08/2023,"Tran, Torres and Joyce",Cosmetic
6,124681,Thomas,Shaw,NaN,26/10/1976,145.94,30/08/2023,"Evans, Griffin and Torres",Cosmetic
7,521807,Kelsey,Pena,F,28/10/1968,161.39,08/02/2023,Miller PLC,Cosmetic
8,504238,Denise,Porter,M,31/10/1957,77.73,12/01/2023,Jackson-Morgan,Restaurant
9,583532,Alexander,Richardson,F,27/10/1974,142.85,07/06/2023,"Blake, Mays and Anderson",Clothing

In [24]:
df.shape # nr of rows and columns

(50000, 9)

In [26]:
df.sample(5) #random sample

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
13839,972418,William,Green,F,01/11/1955,69.05,05/04/2023,Jones and Sons,Restaurant
37855,801558,Lisa,Ryan,F,23/10/1990,75.04,07/09/2023,Brandt-Weaver,Cosmetic
8666,739030,Jennifer,Brown,NaN,27/10/1974,289.70,30/01/2023,"Flowers, Alvarez and Conway",Clothing
47292,674588,Jose,Nelson,M,24/10/1985,208.49,23/09/2023,"Stone, Spears and White",Electronics
34953,873539,Gary,Crawford,M,21/10/1996,90.81,20/06/2023,Davila-Fitzgerald,Restaurant

In [28]:
df.info() #column names, data types, value count

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         50000 non-null  int64
 1   Name                50000 non-null  object
 2   Surname             50000 non-null  object
 3   Gender              44953 non-null  object
 4   Birthdate           50000 non-null  object
 5   Transaction Amount  50000 non-null  float64
 6   Date                50000 non-null  object
 7   Merchant Name       50000 non-null  object
 8   Category            50000 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 3.4+ MB

In [30]:
df.describe() #summary stats of integers/floats

        Customer ID  Transaction Amount
count   50000.00000        50000.000000
mean   500136.79696          442.119239
std    288232.43164          631.669724
min        29.00000            5.010000
25%    251191.50000           79.007500
50%    499520.50000          182.195000
75%    749854.25000          470.515000
max    999997.00000         2999.880000

In [31]:
df.describe(include='object') #summary stats incl objects

,Name,Surname,Gender,Birthdate,Date,Merchant Name,Category
count,50000,50000,44953,50000,50000,50000,50000
unique,690,1000,2,58,287,36939,6
top,Michael,Smith,F,01/11/1954,30/06/2023,Smith Ltd,Restaurant
freq,1167,1095,22713,914,200,69,8413

In [34]:
# How to look at one column
df['Gender']

#on this column we can calc some things
df['Gender'].unique()

array(['F', nan, 'M'], dtype=object)

In [36]:
df['Gender'] # access column by a name, we can access several columns

df.Gender # accessing column with attribute; we access same column but cant use spaces in column name and can only access 1 column

df.iloc[:, 3] # all rows with :, accessing column with index [row, column]

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [37]:
# value counts

df['Gender'].value_counts() # drops na my default

Gender
F    22713
M    22240
Name: count, dtype: int64

In [38]:
# value counts

df['Gender'].value_counts(dropna=False) # keep na

Gender
F      22713
M      22240
NaN     5047
Name: count, dtype: int64

In [40]:
df.isna() #binary values, True=empty; in binary False = 0, True = 1

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
49995,False,False,False,False,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False
49999,False,False,False,False,False,False,False,False,False

In [41]:
df.isna().sum()

Customer ID              0
Name                     0
Surname                  0
Gender                5047
Birthdate                0
Transaction Amount       0
Date                     0
Merchant Name            0
Category                 0
dtype: int64

In [43]:
df.notna().sum()

Customer ID           50000
Name                  50000
Surname               50000
Gender                44953
Birthdate             50000
Transaction Amount    50000
Date                  50000
Merchant Name         50000
Category              50000
dtype: int64

In [44]:
df.notna().all() #check if all values not empty

Customer ID            True
Name                   True
Surname                True
Gender                False
Birthdate              True
Transaction Amount     True
Date                   True
Merchant Name          True
Category               True
dtype: bool

In [45]:
### Drop empty values

df.dropna() #did not override existing df

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics
5,576539,Monica,Bartlett,F,20/10/2001,99.14,24/08/2023,"Tran, Torres and Joyce",Cosmetic
...,...,...,...,...,...,...,...,...,...
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [49]:
df_new_dataframe = df.dropna() # save it in new df

In [47]:
#how to override existing dataframe?
df.dropna(inplace=True) #specify that want to override existing dataframe

In [48]:
# Saving the cleaned file
df.to_csv('cleaned_data.csv')